[package]
name = "sophon_tweets"
version = "0.1.0"
authors = ["Jacob Rosenthal <jacobrosenthal@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
ctrlc = "3.1.4"
web3 = "0.13.0"
futures-micro = "0.3.1"
url = "1.7.2"
oauthcli = "1.0.4"
rustc-hex = "2.1.0"
ethabi = "12.0.0"
reqwest = "0.9.16"
